/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cabañas;

/**
 *
 * @author laptop
 */
public class Cabañas_Eliminar extends javax.swing.JFrame {

    /**
     * Creates new form Cabañas_Modificar
     */
    public Cabañas_Eliminar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NumCabLabel = new javax.swing.JLabel();
        NumCabS = new javax.swing.JSpinner();
        TipCabLabel = new javax.swing.JLabel();
        NumPerLabel = new javax.swing.JLabel();
        DesCabLabel = new javax.swing.JLabel();
        EstaLabel = new javax.swing.JLabel();
        PrecioLab = new javax.swing.JLabel();
        EliCabB = new javax.swing.JButton();
        TCab = new javax.swing.JLabel();
        NPer = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        DCab = new javax.swing.JTextArea();
        EsCab = new javax.swing.JLabel();
        PCab = new javax.swing.JLabel();
        UsCa = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        IniCab = new javax.swing.JMenu();
        NuevCab = new javax.swing.JMenu();
        ModCab = new javax.swing.JMenu();
        EliCab = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NumCabLabel.setText("Numero de cabaña");

        TipCabLabel.setText("Tipo de cabaña");

        NumPerLabel.setText("Numero de personas");

        DesCabLabel.setText("Descripcion");

        EstaLabel.setText("Estatus");

        PrecioLab.setText("Precio");

        EliCabB.setText("Eliminar");
        EliCabB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliCabBActionPerformed(evt);
            }
        });

        TCab.setText("Plus");

        NPer.setText("7");

        DCab.setColumns(20);
        DCab.setRows(5);
        DCab.setText("Gran cabaña\n");
        jScrollPane2.setViewportView(DCab);

        EsCab.setText("Disponible");

        PCab.setText("399 la noche");

        UsCa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UsCa.setIcon(new javax.swing.ImageIcon("C:\\Cursos\\Java\\POO\\Cabañas\\img\\IconIniUs.png")); // NOI18N
        UsCa.setText("Usuario");
        UsCa.setPreferredSize(new java.awt.Dimension(100, 100));

        IniCab.setText("Inicio");
        jMenuBar1.add(IniCab);

        NuevCab.setText("Nueva");
        jMenuBar1.add(NuevCab);

        ModCab.setText("Modificar");
        jMenuBar1.add(ModCab);

        EliCab.setText("Eliminar");
        jMenuBar1.add(EliCab);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(UsCa, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EliCabB)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NumCabLabel)
                    .addComponent(TipCabLabel)
                    .addComponent(NumPerLabel)
                    .addComponent(DesCabLabel)
                    .addComponent(EstaLabel)
                    .addComponent(PrecioLab))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EsCab)
                    .addComponent(NumCabS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TCab)
                    .addComponent(NPer)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PCab))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumCabLabel)
                    .addComponent(NumCabS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TipCabLabel)
                    .addComponent(TCab))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumPerLabel)
                    .addComponent(NPer))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DesCabLabel)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EstaLabel)
                    .addComponent(EsCab))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrecioLab)
                    .addComponent(PCab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EliCabB)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 18, Short.MAX_VALUE)
                        .addComponent(UsCa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EliCabBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliCabBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EliCabBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cabañas_Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cabañas_Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cabañas_Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cabañas_Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cabañas_Eliminar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea DCab;
    private javax.swing.JLabel DesCabLabel;
    private javax.swing.JMenu EliCab;
    private javax.swing.JButton EliCabB;
    private javax.swing.JLabel EsCab;
    private javax.swing.JLabel EstaLabel;
    private javax.swing.JMenu IniCab;
    private javax.swing.JMenu ModCab;
    private javax.swing.JLabel NPer;
    private javax.swing.JMenu NuevCab;
    private javax.swing.JLabel NumCabLabel;
    private javax.swing.JSpinner NumCabS;
    private javax.swing.JLabel NumPerLabel;
    private javax.swing.JLabel PCab;
    private javax.swing.JLabel PrecioLab;
    private javax.swing.JLabel TCab;
    private javax.swing.JLabel TipCabLabel;
    private javax.swing.JLabel UsCa;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
