/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cabañas;

/**
 *
 * @author laptop
 */
public class Cabañas_Modificar extends javax.swing.JFrame {

    /**
     * Creates new form Cabañas_Modificar
     */
    public Cabañas_Modificar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NumCabCabM = new javax.swing.JLabel();
        NcCabM = new javax.swing.JSpinner();
        TipCabCabM = new javax.swing.JLabel();
        TiCabM = new javax.swing.JTextField();
        NumPerCabM = new javax.swing.JLabel();
        NpCabM = new javax.swing.JSpinner();
        DesCCabM = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DeCabM = new javax.swing.JTextArea();
        EsCabM = new javax.swing.JLabel();
        ECabM = new javax.swing.JTextField();
        PreCabM = new javax.swing.JLabel();
        PrCabM = new javax.swing.JTextField();
        ModiCabM = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        IniCabM = new javax.swing.JMenu();
        NueCabM = new javax.swing.JMenu();
        ModCabM = new javax.swing.JMenu();
        EliCabM = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NumCabCabM.setText("Numero de cabaña");

        TipCabCabM.setText("Tipo de cabaña");

        TiCabM.setText("Plus");
        TiCabM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TiCabMActionPerformed(evt);
            }
        });

        NumPerCabM.setText("Numero de personas");

        DesCCabM.setText("Descripcion");

        DeCabM.setColumns(20);
        DeCabM.setRows(5);
        jScrollPane1.setViewportView(DeCabM);

        EsCabM.setText("Estatus");

        PreCabM.setText("Precio");

        ModiCabM.setText("Modificar");

        IniCabM.setText("Inicio");
        jMenuBar1.add(IniCabM);

        NueCabM.setText("Nueva");
        jMenuBar1.add(NueCabM);

        ModCabM.setText("Modificar");
        jMenuBar1.add(ModCabM);

        EliCabM.setText("Eliminar");
        jMenuBar1.add(EliCabM);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NumCabCabM)
                    .addComponent(TipCabCabM)
                    .addComponent(NumPerCabM)
                    .addComponent(DesCCabM)
                    .addComponent(EsCabM)
                    .addComponent(PreCabM))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NpCabM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NcCabM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TiCabM, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ECabM, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PrCabM, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ModiCabM)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumCabCabM)
                    .addComponent(NcCabM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TipCabCabM)
                    .addComponent(TiCabM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumPerCabM)
                    .addComponent(NpCabM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DesCCabM)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ECabM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EsCabM))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PreCabM)
                    .addComponent(PrCabM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ModiCabM)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TiCabMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TiCabMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TiCabMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cabañas_Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cabañas_Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cabañas_Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cabañas_Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cabañas_Modificar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea DeCabM;
    private javax.swing.JLabel DesCCabM;
    private javax.swing.JTextField ECabM;
    private javax.swing.JMenu EliCabM;
    private javax.swing.JLabel EsCabM;
    private javax.swing.JMenu IniCabM;
    private javax.swing.JMenu ModCabM;
    private javax.swing.JButton ModiCabM;
    private javax.swing.JSpinner NcCabM;
    private javax.swing.JSpinner NpCabM;
    private javax.swing.JMenu NueCabM;
    private javax.swing.JLabel NumCabCabM;
    private javax.swing.JLabel NumPerCabM;
    private javax.swing.JTextField PrCabM;
    private javax.swing.JLabel PreCabM;
    private javax.swing.JTextField TiCabM;
    private javax.swing.JLabel TipCabCabM;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
